# Generated by Django 4.0.6 on 2022-07-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nick', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120)),
                ('best_score', models.IntegerField(default=0)),
                ('num_matches', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
