# Generated by Django 4.0.6 on 2022-07-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='num_questions',
            field=models.IntegerField(default=0),
        ),
    ]
